env:
  MVN_CMD: ./mvnw --no-transfer-progress -B
jobs:
  code-coverage:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        check-latest: true
        distribution: zulu
        java-version: '8'
    - continue-on-error: true
      name: Install softhsm2
      run: sudo apt-get install -y softhsm2
    - continue-on-error: true
      name: Install opensc
      run: sudo apt-get install -y opensc
    - continue-on-error: true
      name: Ensure SoftHSM user configuration
      run: impl/src/test/scripts/softhsm configure
    - continue-on-error: true
      name: Populate SoftHSM with JJWT test keys
      run: impl/src/test/scripts/softhsm import
    - continue-on-error: true
      name: Wait to start
      run: sleep 90s
      shell: bash
    - continue-on-error: true
      name: Code Coverage
      run: "${{env.MVN_CMD}} clover:setup test && \\\n  ${{env.MVN_CMD}} -pl . clover:clover\
        \ clover:check coveralls:report \\\n    -DrepoToken=\"${{ secrets.GITHUB_TOKEN\
        \ }}\" \\\n    -DserviceName=github \\\n    -DserviceBuildNumber=\"${{ env.GITHUB_RUN_ID\
        \ }}\"\n"
  license-check:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        check-latest: true
        distribution: zulu
        java-version: '8'
    - continue-on-error: true
      name: License Check
      run: '${{env.MVN_CMD}} license:check

        '
  oracle:
    name: jdk-${{ matrix.java }}-oracle
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: oracle-actions/setup-java@v1
      with:
        release: ${{ matrix.java }}
    - continue-on-error: true
      name: Install softhsm2
      run: sudo apt-get install -y softhsm2
    - continue-on-error: true
      name: Install opensc
      run: sudo apt-get install -y opensc
    - continue-on-error: true
      name: Ensure SoftHSM user configuration
      run: impl/src/test/scripts/softhsm configure
    - continue-on-error: true
      name: Populate SoftHSM with JJWT test keys
      run: impl/src/test/scripts/softhsm import
    - continue-on-error: true
      name: Build
      run: ${{env.MVN_CMD}} verify -Possrh -Dgpg.skip=true
    strategy:
      matrix:
        java:
        - '17'
  temurin:
    name: jdk-${{ matrix.java }}-temurin
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        check-latest: true
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Install softhsm2
      run: sudo apt-get install -y softhsm2
    - continue-on-error: true
      name: Install opensc
      run: sudo apt-get install -y opensc
    - continue-on-error: true
      name: Ensure SoftHSM user configuration
      run: impl/src/test/scripts/softhsm configure
    - continue-on-error: true
      name: Populate SoftHSM with JJWT test keys
      run: impl/src/test/scripts/softhsm import
    - continue-on-error: true
      name: Build
      run: ${{env.MVN_CMD}} verify -Possrh -Dgpg.skip=true
    strategy:
      matrix:
        java:
        - '8'
        - '11'
        - '17'
        - '18'
  zulu:
    env:
      JDK_MAJOR_VERSION: ${{ matrix.java }}
    name: jdk-${{ matrix.java }}-zulu
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        check-latest: true
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Install softhsm2
      run: sudo apt-get install -y softhsm2
    - continue-on-error: true
      name: Install opensc
      run: sudo apt-get install -y opensc
    - continue-on-error: true
      name: Ensure SoftHSM user configuration
      run: impl/src/test/scripts/softhsm configure
    - continue-on-error: true
      name: Populate SoftHSM with JJWT test keys
      run: impl/src/test/scripts/softhsm import
    - continue-on-error: true
      name: Build
      run: 'if [ "$JDK_MAJOR_VERSION" == "7" ]; then export MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=128m";
        fi

        ${{env.MVN_CMD}} verify -Possrh -Dgpg.skip=true

        '
    strategy:
      matrix:
        java:
        - '7'
        - '8'
        - '9'
        - '11'
        - '12'
        - '13'
        - '14'
        - '15'
        - '16'
        - '17'
        - '18'
        - '21'
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
